

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo run k8s_hello_world!
  displayName: '1st run'



trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  versionNumber: '1.0.0'

steps:
- task: replacetokens@3
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)'
    targetFiles: 'combined_config.yaml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
