trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  versionNumber: '1.0.0'

jobs:
- job: RunHelloWorld
  displayName: 'Run Hello World'
  steps:
  - script: echo run k8s_hello_world!
    displayName: '1st run'

- job: ProcessYAML
  displayName: 'Process YAML File'
  steps:
  - task: 
    inputs:
      rootDirectory: '$(System.DefaultWorkingDirectory)'
      targetFiles: 'combined_config.yaml'
      encoding: 'auto'
      writeBOM: true
      actionOnMissing: 'warn'
      keepToken: false
      tokenPrefix: '#{'
      tokenSuffix: '}#'
